#!/bin/sh
set -e
#set -x

lib=svn-to-git.utils.sh
self=$(readlink -f $0)
selflib=$(dirname $self)/$lib
. "$selflib"

test -n "$1" || exit 0
test -d "$1" || exit 0
test -n "$2" || exit 0
test ! -d "$2" || exit 0

cp -a "$1" "$2"

cd "$2"

# CVS history
add_parent glue/svn-r1 master-cvs

# there were commits on the tag afterwards
reparent r436 r435
git branch -m svn/tags/1.1.0 1.1
git branch svn/tags/1.1.0 r436

# tags
branch_to_tag svn/tags/REL-0.9 0.9 master
for t in 1.0e 1.1.0 1.2.0 1.2.1 1.3.0 1.3.1
do
	branch_to_tag svn/tags/$t $t master
done

# fixup tag and branch predecessors
add_parent r755 r754
reparent r444 r443
reparent r1086 1.2.0
reparent r1173 1.2.1
reparent r1507 r1505

# redo the merges properly
add_parent r161 r160
add_parent r212 r210
add_parent r242 r241
add_parent r384 r382
add_parent r576 r539
add_parent r655 r654
add_parent r1090 r1088
add_parent r1174 r801
add_parent r1240 r1239
add_parent r1348 r1319
add_parent r1504 r1503

# empty branches
undo_empty_branch_head_commit svn/ceph_aio
undo_empty_branch_head_commit svn/STLport
undo_empty_branch_head_commit svn/RB-0.9
undo_empty_branch_head_commit svn/1.0
git checkout master
git branch -d svn/ceph_aio
git branch -d svn/STLport
git branch -d svn/RB-0.9
git branch -d svn/1.0
git branch -d 1.1

# merged branches
git checkout master
git branch -d svn/branches-anbe/reorganize-includes
git branch -d svn/loser_tree_for_ext_merger_in_pq
git branch -d svn/avoid_4GB_memlimit
git branch -d svn/parallel
git branch -d svn/1.2.0_bugfixes
git branch -d svn/wbtl
git branch -d svn/request_cancel
git branch -d svn/file_per_block
git branch -d svn/matrix

git checkout svn/parallel_pipelining
git branch -d svn/parallel_mode_pipelining
git branch -d svn/pipelining
git branch -d svn/parallel_pq

git checkout svn/unordered_map
git branch -d svn/hash_map

git checkout svn/posixaio
git branch -d svn/iolayer

git checkout svn/kernelaio
git branch -d svn/libaio

# to be kept
git branch -m svn/1.3 1.3
git branch -m svn/comparison_based_stable_sort comparison_based_stable_sort
git branch -m svn/kernelaio kernelaio
git branch -m svn/posixaio posixaio
git branch -m svn/unordered_map unordered_map
git branch -m svn/parallel_pipelining parallel_pipelining
git branch -m svn/parallel_pipelining_integration parallel_pipelining_integration

# obsolete branches
git branch -m svn/TRY-DYN_VEC_PARAM attic/TRY-DYN_VEC_PARAM
git branch -m svn/branches-anbe/dump-pq attic/dump-pq
git branch -m svn/trim_file attic/trim_file
git branch -m svn/demsort_adaptations attic/demsort_adaptations


git checkout from-svn-to-git
script=$(basename $0)
cp -a "$self" "$script"
cp -a "$selflib" "$lib"
git add "$script" "$lib"
git commit -m "cleaning up the imported svn history, part 2"
