#!/bin/bash -x

set -e

rm -rvf stxxl
git clone git@github.com:bingmann/stxxl

cd stxxl
git filter-branch --tree-filter '
  rm -rf \
    CVS \
    STXXL.prj \
    STXXL.prj.389 \
    STXXL.pws \
    algo/.cccc \
    algo/.gitignore \
    algo/.stxxl \
    algo/CVS \
    algo/GNUmakefile \
    algo/Makefile \
    algo/Makefile.common \
    algo/adaptor.h \
    algo/copy_and_sort_file.cpp \
    algo/gen_file.cpp \
    algo/inmemsort.h \
    algo/intksort.h \
    algo/koptprefetcher.h.back \
    algo/kprefetcher.h.back \
    algo/ksort.cpp \
    algo/ksort.h \
    algo/ksort_exp.h \
    algo/loosertree.h \
    algo/losertree.h \
    algo/random_shuffle.h \
    algo/run_cursor.h \
    algo/scan.h \
    algo/sort.cpp \
    algo/sort.h \
    algo/sort.h.back \
    algo/sort_file.cpp \
    algo/stable_ksort.cpp \
    algo/stable_ksort.h \
    algo/test.cpp \
    algo/test_bad_cmp.cpp \
    algo/test_ksort.cpp \
    algo/test_ksort1.cpp \
    algo/test_ksort_all_parameters.cpp \
    algo/test_matrix.cpp \
    algo/test_parallel_sort.cpp \
    algo/test_random_shuffle.cpp \
    algo/test_scan.cpp \
    algo/test_sort.cpp \
    algo/test_sort1.cpp \
    algo/test_sort_all_parameters.cpp \
    algo/test_sort_all_parameters.h \
    algo/test_stable_ksort.cpp \
    algo/test_stable_ksort1.cpp \
    algo/test_stable_ksort_all_parameters.cpp \
    apps/.pure \
    apps/.stxxl \
    apps/CVS \
    apps/Makefile \
    apps/foo.c \
    apps/foo.cpp \
    apps/gmon.out \
    apps/intkeysort.h \
    apps/keysort.h \
    apps/kloosertree.h \
    apps/kprefetcher.h \
    apps/loosertree.h \
    apps/mkeysort.cpp \
    apps/mkeysort.h \
    apps/msort.cpp \
    apps/msort.h \
    apps/peter \
    apps/peter/CVS \
    apps/peter/CVS/Repository \
    apps/peter/Makefile \
    apps/peter/fastsort.c \
    apps/peter/fastsort.h \
    apps/peter/mt-real.c \
    apps/peter/notes.asc \
    apps/peter/petersort.txt \
    apps/peter/radixsort.C \
    apps/peter/radixsort2.C \
    apps/peter/util.h \
    apps/prefetcher.h \
    apps/quantify_sort \
    apps/simdisk.cpp \
    common/.gitignore \
    common/CVS \
    common/debug.obj \
    common/log.obj \
    common/myutils.h \
    common/perm.h \
    common/perm_old.h \
    common/rand.obj \
    common/rwlock.h \
    common/test_argument_helper.cpp \
    common/test_globals.cpp \
    common/tuple.h \
    common/utils_ledasm.h \
    config_example \
    config_example_win \
    containers \
    contrib \
    doc/ \
    doxy/ \
    doxymain.h \
    doxymain.h~ \
    examples/ \
    homepage/ \
    images/ \
    include/.gitignore \
    include/Argument_helper.h \
    include/bits/intel_compatibility.h \
    include/contrib \
    include/contrib/argument_helper.h \
    include/contrib/dump_rusage.h \
    include/stxxl.h \
    include/stxxl/.gitignore \
    include/stxxl/algorithm \
    include/stxxl/all \
    include/stxxl/bits/.gitignore \
    include/stxxl/bits/algo/.gitignore \
    include/stxxl/bits/algo/adapter.h \
    include/stxxl/bits/algo/adaptor.h \
    include/stxxl/bits/algo/trigger_entry.h \
    include/stxxl/bits/algo/bid_adapter.h \
    include/stxxl/bits/algo/inmemsort.h \
    include/stxxl/bits/algo/intksort.h \
    include/stxxl/bits/algo/ksort.h \
    include/stxxl/bits/algo/losertree.h \
    include/stxxl/bits/algo/random_shuffle.h \
    include/stxxl/bits/algo/run_cursor.h \
    include/stxxl/bits/algo/scan.h \
    include/stxxl/bits/algo/sort.h \
    include/stxxl/bits/algo/sort_base.h \
    include/stxxl/bits/algo/sort_helper.h \
    include/stxxl/bits/algo/stable_ksort.h \
    include/stxxl/bits/algo/winner_tree.h \
    include/stxxl/bits/common/.gitignore \
    include/stxxl/bits/common/binary_buffer.h \
    include/stxxl/bits/common/custom_stats.h \
    include/stxxl/bits/common/intel_compatibility.h \
    include/stxxl/bits/common/is_heap.h \
    include/stxxl/bits/common/is_sorted.h \
    include/stxxl/bits/common/rwlock.h \
    include/stxxl/bits/common/swap_vector.h \
    include/stxxl/bits/common/tuple.h \
    include/stxxl/bits/common/utils_ledasm.h \
    include/stxxl/bits/common/winner_tree.h \
    include/stxxl/bits/containers \
    include/stxxl/bits/parallel \
    include/stxxl/bits/stream \
    include/stxxl/bits/utils/external_shared_ptr.h \
    include/stxxl/bits/utils/malloc.h \
    include/stxxl/bits/utils/malloc_count.h \
    include/stxxl/bits/utils/stacktrace.h \
    include/stxxl/deque \
    include/stxxl/ksort \
    include/stxxl/mallocstats \
    include/stxxl/map \
    include/stxxl/parallel_priority_queue \
    include/stxxl/priority_queue \
    include/stxxl/queue \
    include/stxxl/random_shuffle \
    include/stxxl/scan \
    include/stxxl/sequence \
    include/stxxl/sort \
    include/stxxl/sorter \
    include/stxxl/stable_ksort \
    include/stxxl/stack \
    include/stxxl/stream \
    include/stxxl/unordered_map \
    include/stxxl/vector \
    io/.gitignore \
    io/.pure \
    io/CVS \
    io/flush \
    io/foo \
    io/min_sort_time \
    io/simdisk_file.h.does_not_work \
    io/syscall_rates \
    lazy \
    lib/.gitignore \
    lib/libstxxl.symbols \
    lib/utils \
    lib/utils/malloc_count.cpp \
    local \
    logo \
    misc/.gitignore \
    misc/analyze-include-dependencies.pl \
    misc/buildbot-configure \
    misc/buildbot-master \
    misc/buildbot-master/master.cfg \
    misc/buildbot-master/master.cfg.sample \
    misc/buildbot-master/master_secret.py.sample \
    misc/buildbot-run-tests-minimal \
    misc/buildbot-test-autoconfig \
    misc/concat-lines \
    misc/diskbench-avgdat.sh \
    misc/diskbench.mk \
    misc/do-release.txt \
    misc/fix-properties \
    misc/floating-average \
    misc/icpc.supp \
    misc/iostat-plot.mk \
    misc/libc-2.11.supp \
    misc/libc-2.7.supp \
    misc/libc-leak.supp \
    misc/libgomp.supp \
    misc/record-load-iostat \
    misc/remove-unless \
    misc/run-all-tests \
    misc/run-all-tests-windows.bat \
    misc/uncrustify.mk \
    misc/valgrind.supp \
    mng/.gitignore \
    mng/.stxxl \
    mng/CVS \
    mng/mng.h.oldtmpl \
    mng/mng.obj \
    stream \
    stxxl.ncb \
    stxxl.sln \
    stxxl.suo \
    stxxl.vcproj \
    stxxl/algo/stable_ksort.h \
    stxxl/algorithm \
    stxxl/all \
    stxxl/bits/algo/adaptor.h \
    stxxl/bits/algo/inmemsort.h \
    stxxl/bits/algo/intksort.h \
    stxxl/bits/algo/ksort.h \
    stxxl/bits/algo/losertree.h \
    stxxl/bits/algo/random_shuffle.h \
    stxxl/bits/algo/run_cursor.h \
    stxxl/bits/algo/scan.h \
    stxxl/bits/algo/sort.h \
    stxxl/bits/algo/stable_ksort.h \
    stxxl/bits/common/rwlock.h \
    stxxl/bits/common/tuple.h \
    stxxl/bits/common/utils_ledasm.h \
    stxxl/bits/containers \
    stxxl/bits/stream \
    stxxl/bits/utils \
    stxxl/bits/utils/malloc.h \
    stxxl/common/utils_ledasm.h \
    stxxl/containers \
    stxxl/deque \
    stxxl/ksort \
    stxxl/mallocstats \
    stxxl/map \
    stxxl/priority_queue \
    stxxl/queue \
    stxxl/scan \
    stxxl/sort \
    stxxl/stable_ksort \
    stxxl/stack \
    stxxl/stream \
    stxxl/stxxl \
    stxxl/stxxl.h \
    stxxl/utils \
    stxxl/vector \
    test/.gitignore \
    test/.stxxl \
    test/CVS \
    test/Makefile \
    test/WinGUI \
    test/block.cpp \
    test/compile-stxxl-headers \
    test/compile-stxxl-headers/.gitignore \
    test/compile-stxxl-headers/Makefile \
    test/dev.cpp \
    test/features.cpp \
    test/stack_band.cpp \
    test/template_handler.cpp \
    test/test_thr.cpp \
    test/threads.cpp \
    tests/algo/test_bad_cmp.cpp \
    tests/algo/test_ksort.cpp \
    tests/algo/test_ksort_all_parameters.cpp \
    tests/algo/test_parallel_sort.cpp \
    tests/algo/test_random_shuffle.cpp \
    tests/algo/test_scan.cpp \
    tests/algo/test_sort.cpp \
    tests/algo/test_sort_all_parameters.cpp \
    tests/algo/test_sort_all_parameters.h \
    tests/algo/test_stable_ksort.cpp \
    tests/algo/test_stable_ksort_all_parameters.cpp \
    tests/common/test_argument_helper.cpp \
    tests/common/test_binary_buffer.cpp \
    tests/common/test_external_shared_ptr.cpp \
    tests/common/test_globals.cpp \
    tests/common/test_swap_vector.cpp \
    tests/common/test_tuple.cpp \
    tests/common/test_winner_tree.cpp \
    tests/compile \
    tests/compile/Makefile \
    tests/containers \
    tests/parallel \
    tests/stream \
    tools/algo/CMakeLists.txt \
    tools/algo/copy_and_sort_file.cpp \
    tools/algo/sort_file.cpp \
    tools/algo/test_bad_cmp.cpp \
    tools/algo/test_ksort.cpp \
    tools/algo/test_ksort_all_parameters.cpp \
    tools/algo/test_parallel_sort.cpp \
    tools/algo/test_random_shuffle.cpp \
    tools/algo/test_scan.cpp \
    tools/algo/test_sort.cpp \
    tools/algo/test_sort_all_parameters.cpp \
    tools/algo/test_sort_all_parameters.h \
    tools/algo/test_stable_ksort.cpp \
    tools/algo/test_stable_ksort_all_parameters.cpp \
    tools/benchmark_pqs.cpp \
    tools/benchmark_pqs_helper.h \
    tools/benchmark_pqueue.cpp \
    tools/benchmark_sort.cpp \
    tools/benchmarks/CMakeLists.txt \
    tools/benchmarks/GNUmakefile.old \
    tools/benchmarks/README \
    tools/benchmarks/app_config.h \
    tools/benchmarks/bench_pqueue.cpp \
    tools/benchmarks/benchmark_naive_matrix.cpp \
    tools/benchmarks/berkeley_db_benchmark.cpp \
    tools/benchmarks/matrix_benchmark.cpp \
    tools/benchmarks/monotonic_pq.cpp \
    tools/benchmarks/pq_benchmark.cpp \
    tools/benchmarks/run_bdb_test \
    tools/benchmarks/stack_benchmark.cpp \
    tools/benchmarks/tpie_stack_benchmark.cpp \
    tools/common/test_argument_helper.cpp \
    tools/common/test_globals.cpp \
    tools/containers \
    tools/extras/CMakeLists.txt \
    tools/extras/benchmark_disk_and_flash.cpp \
    tools/extras/iobench_scatter_in_place.cpp \
    tools/extras/pq_param.cpp \
    tools/mallinfo.cpp \
    tools/mlock.cpp \
    tools/stream \
    tools/stream/CMakeLists.txt \
    tools/utils/CMakeLists.txt \
    tools/utils/malloc.cpp \
    tools/utils/mlock.cpp \
    tools/utils/pq_param.cpp \
    utils/.gitignore \
    utils/CMakeLists.txt \
    utils/CVS \
    utils/GNUmakefile \
    utils/Makefile \
    utils/Makefile.common \
    utils/malloc.cpp \
    utils/malloc.h \
    utils/mlock.cpp \
    utils/off_t_size.cpp \
    utils/pq_param.cpp \
    utils/stxxl.log
' --prune-empty --tag-name-filter cat -- --all

for t in `git tag -l`; do
    git tag stxxl-$t $t
    git tag -d $t
done

# git filter-branch --tree-filter "
# " --prune-empty --tag-name-filter cat -f -- --all

rm -rf .git/refs/original
git reflog expire --expire=now --all
git gc --prune=now
